"""Purpose:
    Unit tests for document_structure_analysis.recommend_from_normalized (Phase 4.5 Wave 3).

Key Input Dependencies:
    - pytest and the plugin-local tests in this namespace
    - json
    - pathlib
    - pytest
    - document_structure_analysis

Unit tests for document_structure_analysis.recommend_from_normalized (Phase 4.5 Wave 3).

Consumes real `normalized-source-document` v1 fixtures generated by
running `source-document-extraction`'s installed `extract_and_normalize`
against the same synthetic .docx fixtures Wave 2 used
(small_single.docx -> "single" strategy; repeated_headings.docx ->
"chunked" strategy, one topic per Gadget module).

Ported from docx-to-content's tests/unit/test_analyze_structure.py per
the KNOWLEDGE_ANALYSIS-tagged tests that remained after Wave 2's split
(topic-grouping preview, recommendation, draft-plan construction),
adapted to recommend_from_normalized's dict-in/dict-out shape.

Key Functions Index:
    - _load()
    - test_recommends_single_strategy_for_small_single()
    - test_recommends_chunked_strategy_for_repeated_headings()
    - test_recommendation_constants_are_named_and_configurable()
    - test_recommend_strategy_pure_function()
    - test_proposed_topics_preview_for_repeated_headings()
    - test_proposed_topics_present_for_small_single()
    - test_draft_plan_has_source_fingerprint_and_draft_status()
    - test_draft_plan_chunk_anchors_are_structural_not_line_offsets()
    - test_draft_plan_anchor_occurrence_disambiguates_repeated_paths()
    - test_source_not_found_via_missing_required_field_raises()
    - test_result_matches_analysis_plan_contract()"""

import json
from pathlib import Path

import pytest

from document_structure_analysis import recommend_from_normalized, recommend_strategy, MIN_HEADINGS_FOR_CHUNKING, MIN_LINES_FOR_CHUNKING

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"


# Load and validate the analysis-plan fixture from its serialized JSON file.
def _load(name: str) -> dict:
    """Load and validate the analysis-plan fixture from its serialized JSON file."""
    return json.loads((FIXTURES / f"{name}-normalized-source-document.json").read_text())


SMALL_SINGLE = _load("small_single")
REPEATED_HEADINGS = _load("repeated_headings")


# Verify recommends single strategy for small single.
def test_recommends_single_strategy_for_small_single():
    """Verify recommends single strategy for small single."""
    result = recommend_from_normalized(SMALL_SINGLE)
    assert result["strategy"] == "single"
    assert result["recommendation"]["strategy"] == "single"
    assert result["recommendation"]["reasons"]


# Verify recommends chunked strategy for repeated headings.
def test_recommends_chunked_strategy_for_repeated_headings():
    """Verify recommends chunked strategy for repeated headings."""
    result = recommend_from_normalized(REPEATED_HEADINGS)
    assert result["strategy"] == "chunked"
    assert result["recommendation"]["reasons"]


# Verify recommendation constants are named and configurable.
def test_recommendation_constants_are_named_and_configurable():
    """Verify recommendation constants are named and configurable."""
    assert isinstance(MIN_HEADINGS_FOR_CHUNKING, int)
    assert isinstance(MIN_LINES_FOR_CHUNKING, int)


# Verify recommend strategy pure function.
def test_recommend_strategy_pure_function():
    """Verify recommend strategy pure function."""
    result = recommend_strategy(heading_count=10, repeated_path_count=0, line_count=10)
    assert result["strategy"] == "chunked"
    result = recommend_strategy(heading_count=1, repeated_path_count=0, line_count=1)
    assert result["strategy"] == "single"


# ---------------------------------------------------------------------------
# Proposed topic-grouping preview
# ---------------------------------------------------------------------------

def test_proposed_topics_preview_for_repeated_headings():
    """Verify proposed topics preview for repeated headings."""
    result = recommend_from_normalized(REPEATED_HEADINGS)
    proposed = result["proposed_topics"]
    assert [t["title"] for t in proposed] == [
        "Gadget Alpha Module",
        "Gadget Beta Module",
        "Gadget Gamma Module",
    ]
    alpha = proposed[0]
    assert alpha["anchor_count"] == 5
    assert alpha["child_heading_count"] == 4
    assert alpha["first_anchor_path"] == ["Gadget Alpha Module"]
    assert alpha["approx_size_chars"] > 0
    assert alpha["topic_id"].startswith("gadget-alpha-module--")


# Verify proposed topics present for small single.
def test_proposed_topics_present_for_small_single():
    """Verify proposed topics present for small single."""
    result = recommend_from_normalized(SMALL_SINGLE)
    proposed = result["proposed_topics"]
    assert isinstance(proposed, list)
    assert len(proposed) >= 1


# ---------------------------------------------------------------------------
# Draft plan: structural anchors + source fingerprint, no raw line offsets
# ---------------------------------------------------------------------------

def test_draft_plan_has_source_fingerprint_and_draft_status():
    """Verify draft plan has source fingerprint and draft status."""
    result = recommend_from_normalized(SMALL_SINGLE)
    assert result["confirmation"]["status"] == "draft"
    assert result["source"]["path"] == SMALL_SINGLE["source_path"]
    assert len(result["source"]["sha256"]) == 64


# Verify draft plan chunk anchors are structural not line offsets.
def test_draft_plan_chunk_anchors_are_structural_not_line_offsets():
    """Verify draft plan chunk anchors are structural not line offsets."""
    result = recommend_from_normalized(REPEATED_HEADINGS)
    anchors = result["chunk_anchors"]
    assert len(anchors) > 0
    for anchor in anchors:
        assert "line" not in anchor
        assert "line_number" not in anchor
        assert anchor["stable_key"]
        assert anchor["source_heading_path"]


# Verify draft plan anchor occurrence disambiguates repeated paths.
def test_draft_plan_anchor_occurrence_disambiguates_repeated_paths():
    """Verify draft plan anchor occurrence disambiguates repeated paths."""
    result = recommend_from_normalized(REPEATED_HEADINGS)
    getting_started = [a for a in result["chunk_anchors"] if a["heading_text"] == "Getting Started"]
    assert len(getting_started) >= 2
    keys = {a["stable_key"] for a in getting_started}
    assert len(keys) == len(getting_started)
    paths = {tuple(a["source_heading_path"]) for a in getting_started}
    assert len(paths) == len(getting_started)


# Verify source not found via missing required field raises.
def test_source_not_found_via_missing_required_field_raises():
    """Verify source not found via missing required field raises."""
    with pytest.raises(KeyError):
        recommend_from_normalized({})


# Verify result matches analysis plan contract.
def test_result_matches_analysis_plan_contract():
    """Verify result matches analysis plan contract."""
    from plan_schema.analysis_plan import validate

    result = recommend_from_normalized(SMALL_SINGLE)
    validate(result)  # raises if required fields are missing
