"""
wave_script_generation.py
===========================

Purpose:
    Stage 3b (`scaffold-migration-wave-scripts`) logic: read a
    dependency-matrix.json-shaped dict (stage 3a's
    ``dependency_graph.build_dependency_matrix`` output) and synthesize one
    Python wave-script skeleton per computed wave, plus a single wave guide
    document listing every wave as a discrete test -> deploy -> retest step
    (`rules/test-driven-wave-deployment.md`) -- never a single unattended
    run-everything orchestrator (`rules/deployment-decision-principles.md`).

    Deliberately a thin templating layer, not full schema synthesis: the
    matrix only carries name/objectType/dependsOn, never full field
    definitions, so a generated script's provisioning schema body is an
    honest TODO placeholder -- never fabricated field data. Every object
    name/type that does appear in a generated script comes only from the
    matrix; nothing from the style-reference templates
    (`assets/migration-planning/wave-script-template.example.py`,
    `assets/migration-planning/wave-guide-template.md`) is copied into generated output.

Layer: sharepoint-site-migration / stage 3b (wave script generation)

Key Input Dependencies:
    - provisioning_outcomes.Outcome (symlinked from sharepoint-site-build-and-publish)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence

from provisioning_outcomes import Outcome


@dataclass(frozen=True)
class GeneratedWaveScript:
    """One generated wave script: its 1-based wave number, the object names
    it deploys (in matrix order), and its full source text."""

    wave_number: int
    object_names: tuple[str, ...]
    source: str
    filename: str


@dataclass(frozen=True)
class WaveGenerationResult:
    """Result of generating wave scripts + a wave guide from a dependency
    matrix. ``scripts``/``guide`` are only populated when ``outcome`` is
    ``OBSERVED`` or ``EMPTY`` -- a ``FAILED`` matrix (a blocked/invalid
    dependency graph) never reaches script generation."""

    outcome: str
    scripts: tuple[GeneratedWaveScript, ...] = ()
    guide: str = ""
    issues: tuple[str, ...] = ()


def generate_wave_scripts(matrix: Mapping[str, Any]) -> WaveGenerationResult:
    """Generate one wave script per computed wave in `matrix["waves"]`, plus
    a single wave guide, from a dependency-matrix.json-shaped dict. Refuses
    to generate anything from a matrix whose `outcome` is
    `Outcome.FAILED` (a blocked/invalid dependency graph) -- generating
    scripts from that would mean deploying against a graph already known
    not to resolve."""
    matrix_outcome = matrix.get("outcome")
    if matrix_outcome == Outcome.FAILED:
        return WaveGenerationResult(
            outcome=Outcome.FAILED,
            issues=(
                "dependency-matrix.json outcome is Failed -- refusing to generate wave "
                "scripts from a blocked/invalid dependency graph. Resolve the matrix's "
                "blocking_findings first.",
            ),
        )

    waves: Sequence[Sequence[str]] = matrix.get("waves") or []
    if not waves:
        return WaveGenerationResult(outcome=Outcome.EMPTY, scripts=(), guide="")

    objects_by_name = {obj["name"]: obj for obj in matrix.get("objects", [])}

    scripts: list[GeneratedWaveScript] = []
    for index, wave_names in enumerate(waves, start=1):
        scripts.append(_generate_wave_script(index, wave_names, objects_by_name))

    guide = _generate_wave_guide(scripts)

    return WaveGenerationResult(outcome=Outcome.OBSERVED, scripts=tuple(scripts), guide=guide)


def _generate_wave_script(
    wave_number: int, wave_names: Sequence[str], objects_by_name: Mapping[str, Any]
) -> GeneratedWaveScript:
    object_lines = []
    for name in wave_names:
        obj = objects_by_name.get(name, {})
        object_type = obj.get("objectType", "Unknown")
        depends_on = obj.get("dependsOn", [])
        object_lines.append(f"    # {name} ({object_type}), dependsOn={depends_on!r}")

    objects_comment = "\n".join(object_lines) if object_lines else "    # (no objects)"
    names_repr = ", ".join(repr(n) for n in wave_names)

    source = f'''"""
Generated wave {wave_number} deployment script.

Generated by sharepoint-scaffold-migration-wave-scripts from dependency-matrix.json.
Objects in this wave (name, objectType, dependsOn), taken directly from the
matrix -- never hand-authored:
{objects_comment}

This script is a skeleton: the dependency matrix carries object names/types/
dependsOn only, not full field-level schema, so the ProvisioningSchema body
below is an honest TODO, not fabricated data. Fill in each object's real
schema before running this wave, using sharepoint-site-build-and-publish's existing
ListDef/ContentTypeDef/FieldDef shapes.

Never run every wave unattended in one pass -- see
rules/test-driven-wave-deployment.md. This script deploys ONLY wave {wave_number}.
"""

from __future__ import annotations

# from list_provisioning import ListDef, ProvisioningSchema, CurrentState, plan_provisioning, apply_provisioning

WAVE_NUMBER = {wave_number}
WAVE_OBJECT_NAMES = ({names_repr},)


def build_schema():
    """TODO: populate real field-level schema for each object in
    WAVE_OBJECT_NAMES using sharepoint-site-build-and-publish's existing schema
    types. The dependency matrix does not carry field definitions, so this
    cannot be synthesized mechanically -- fill in by hand before deploying."""
    raise NotImplementedError(
        "wave {wave_number} schema not yet populated -- see WAVE_OBJECT_NAMES for what "
        "belongs here"
    )


def main() -> None:
    """Dry-run by default; requires an explicitly injected executor and a
    plan-derived confirmation token to write anything -- matches
    sharepoint-site-build-and-publish's existing three-gate write safety exactly,
    never reimplemented or weakened here."""
    raise NotImplementedError("populate build_schema() before running this wave script")


if __name__ == "__main__":
    main()
'''

    return GeneratedWaveScript(
        wave_number=wave_number,
        object_names=tuple(wave_names),
        source=source,
        filename=f"plan_wave_{wave_number}.py",
    )


def _generate_wave_guide(scripts: Sequence[GeneratedWaveScript]) -> str:
    lines = [
        "# Wave Deployment Guide",
        "",
        "> Generated by sharepoint-scaffold-migration-wave-scripts from dependency-matrix.json. "
        "Run **one wave at a time** -- never run every wave unattended in one pass. "
        "See `rules/test-driven-wave-deployment.md`.",
        "",
        "## Prerequisites",
        "",
        "- `config.psd1` at the repository root, with a populated `Connection` block.",
        "- This migration's `dependency-matrix.json`.",
        "",
        "## How to use this guide",
        "",
        "For each wave below, in order:",
        "",
        "1. Run the wave's validation check -- expect it to fail (the objects don't exist yet).",
        "2. Deploy the wave (dry-run first, then for real, per sharepoint-site-build-and-publish's existing "
        "three-gate write safety -- injected executor, confirmation token).",
        "3. Re-run the validation check -- confirm it now passes.",
        "4. Only then move to the next wave.",
        "",
    ]

    for script in scripts:
        lines.append(f"## Wave {script.wave_number}")
        lines.append("")
        lines.append(f"**Objects in this wave:** {', '.join(script.object_names)}")
        lines.append("")
        lines.append("```bash")
        lines.append(f"# validation (expect FAIL before deploying)")
        module = script.filename[:-3]
        lines.append(f"python3 -m {module} --check")
        lines.append("")
        lines.append("# deploy (dry-run first)")
        lines.append(f"python3 -m {module} --dry-run")
        lines.append(f"python3 -m {module} --confirm <token>")
        lines.append("")
        lines.append("# validation (expect PASS after deploying)")
        lines.append(f"python3 -m {module} --check")
        lines.append("```")
        lines.append("")
        lines.append("Stop here and confirm this wave's validation passes before continuing.")
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)
