<#
.SYNOPSIS
    Task 8A: Read-only reconciliation of deployed review-manual-topics SKILL.md

.DESCRIPTION
    Inspects AgentAssets/Skills/ folder for any deployed SKILL.md files.
    Records identity, path, frontmatter, timestamp, and calculated SHA-256.
    Compares against repository artifact hash.

    READ-ONLY: No upload, overwrite, delete, or tenant modification.

.EXAMPLE
    .\task-8a-reconcile-deployed-skill.ps1
#>

[CmdletBinding()]
param(
    [string]$ConfigFile = (Join-Path $PSScriptRoot '../../../config.psd1'),
    [string]$TargetSkillName = "review-manual-topics",
    [string]$RepoSkillPath = "plugins/sharepoint-agents-and-skills/skills/review-manual-topics/SKILL.md",
    [string]$RepositorySHA = ""
)

$ErrorActionPreference = "Stop"

if (-not $RepositorySHA) {
    if (-not (Test-Path $RepoSkillPath)) {
        Write-Error "Repository skill file '$RepoSkillPath' not found and no -RepositorySHA supplied."
        exit 1
    }
    $repoBytes = [System.IO.File]::ReadAllBytes((Resolve-Path $RepoSkillPath))
    $repoHasher = [System.Security.Cryptography.SHA256]::Create()
    try {
        $RepositorySHA = [System.BitConverter]::ToString($repoHasher.ComputeHash($repoBytes)).Replace("-", "").ToLower()
    } finally {
        $repoHasher.Dispose()
    }
}

Write-Host "=== SKILL.md DEPLOYMENT RECONCILIATION: $TargetSkillName ===" -ForegroundColor Cyan
Write-Host "Repository SHA-256: $RepositorySHA" -ForegroundColor Yellow
Write-Host ""

if (-not (Test-Path $ConfigFile)) {
    Write-Error "Config file $ConfigFile not found."
    exit 1
}

# --- Workbench connection resolution -------------------------------------
# Single source of truth is the repository-root config.psd1 generated by
# workbench-setup's setup-sharepoint-connection skill, whose canonical shape
# nests connection values under a Connection block. Older plugin-local configs
# used flat top-level keys, so both are accepted and normalized here.
$rawConfig = Import-PowerShellDataFile $ConfigFile
if ($rawConfig.Connection) {
    $config = @{
        SiteUrl  = $rawConfig.Connection.SiteUrl
        ClientId = $rawConfig.Connection.ClientId
        TenantId = $rawConfig.Connection.TenantId
        AuthenticationMode = $rawConfig.Connection.AuthenticationMode
    }
} else {
    $config = $rawConfig
}
Import-Module PnP.PowerShell -ErrorAction Stop

# Authentication
$hasValidAppReg = ($config.ClientId -and $config.TenantId -and `
    $config.ClientId -notlike "*test*" -and $config.ClientId -notlike "*example*" -and `
    $config.TenantId -notlike "*test*" -and $config.TenantId -notlike "*example*")

if ($hasValidAppReg) {
    Connect-PnPOnline -Url $config.SiteUrl -ClientId $config.ClientId -Tenant $config.TenantId -Interactive -ErrorAction Stop
} else {
    Write-Error "No valid app registration in $ConfigFile. Run workbench-setup's setup-sharepoint-connection skill to generate the repository-root config.psd1 with real Connection.ClientId / Connection.TenantId values."
    exit 1
}

Write-Host "Connected to: $($config.SiteUrl)" -ForegroundColor Green
Write-Host ""

# Find AgentAssets library
Write-Host "Searching for AgentAssets library..." -ForegroundColor Cyan
try {
    $agentAssetsLib = Get-PnPList | Where-Object { $_.Title -eq "AgentAssets" }

    if (-not $agentAssetsLib) {
        Write-Host "AgentAssets library NOT FOUND on tenant." -ForegroundColor Red
        Write-Host "DISPOSITION: TASK_8_AGENTASSETS_LIBRARY_NOT_FOUND"
        exit 0
    }

    Write-Host "✓ AgentAssets library found" -ForegroundColor Green
    Write-Host "  Title: $($agentAssetsLib.Title)" -ForegroundColor Gray
    Write-Host "  ID: $($agentAssetsLib.Id)" -ForegroundColor Gray
    Write-Host "  RootFolder: $($agentAssetsLib.RootFolder.ServerRelativeUrl)" -ForegroundColor Gray
    Write-Host ""

    # Check Skills folder
    Write-Host "Checking for Skills subfolder..." -ForegroundColor Cyan
    $skillsFolderPath = "$($agentAssetsLib.RootFolder.ServerRelativeUrl)/Skills"

    try {
        $skillsFolder = Get-PnPFolder -Url $skillsFolderPath -ErrorAction Stop
        Write-Host "✓ Skills folder found" -ForegroundColor Green
        Write-Host "  Path: $($skillsFolder.ServerRelativeUrl)" -ForegroundColor Gray
        Write-Host ""
    } catch {
        Write-Host "✗ Skills folder NOT accessible at $skillsFolderPath" -ForegroundColor Red
        Write-Host "DISPOSITION: TASK_8_SKILLS_FOLDER_NOT_FOUND"
        exit 0
    }

    # Enumerate all skill subfolders. Uses -Identity with the already-resolved $skillsFolder
    # object rather than -FolderSiteRelativeUrl with $skillsFolderPath: that path is
    # SERVER-relative (e.g. "/sites/TargetSite-Dev/AgentAssets/Skills", built from
    # $agentAssetsLib.RootFolder.ServerRelativeUrl above), but -FolderSiteRelativeUrl expects a
    # SITE-relative path (e.g. "AgentAssets/Skills") -- passing the wrong kind silently resolved
    # to zero folders instead of erroring, which previously caused this script to falsely report
    # DISPOSITION: TASK_8_NO_SKILLS_DEPLOYED against a tenant that actually had 2 skills deployed
    # (found 2026-08-03 during Phase 6 native-runtime evaluation prep -- confirmed via direct
    # SharePoint UI screenshot showing sample-test-skill/ and review-manual-topics/ both present).
    # -Identity sidesteps the site-relative-vs-server-relative ambiguity entirely.
    Write-Host "Enumerating skill subfolders..." -ForegroundColor Cyan
    $skillFolders = Get-PnPFolderInFolder -Identity $skillsFolder -ErrorAction Stop

    if ($skillFolders.Count -eq 0) {
        Write-Host "No skill folders found in Skills/." -ForegroundColor Yellow
        Write-Host "DISPOSITION: TASK_8_NO_SKILLS_DEPLOYED"
        exit 0
    }

    Write-Host "Found $($skillFolders.Count) skill folder(s):" -ForegroundColor Green
    Write-Host ""

    $deployedSkills = @()

    foreach ($folder in $skillFolders) {
        $folderName = $folder.Name
        Write-Host "Skill: $folderName" -ForegroundColor Yellow
        Write-Host "  Path: $($folder.ServerRelativeUrl)" -ForegroundColor Gray

        # Look for SKILL.md in this folder
        $skillMdPath = "$($folder.ServerRelativeUrl)/SKILL.md"

        try {
            # -AsFileObject (not -AsFile) returns a file object without writing to disk --
            # -AsFile belongs to a different parameter set ("Save to local path") that requires
            # -Path, which caused PowerShell to interactively prompt for a Path value here
            # (found 2026-08-03 alongside the -FolderSiteRelativeUrl bug above, same debugging
            # pass). The second Get-PnPFile call below genuinely needs -AsFile (it supplies
            # -Path $tempPath) and is correct as-is.
            $file = Get-PnPFile -Url $skillMdPath -AsFileObject -ErrorAction Stop

            Write-Host "  ✓ SKILL.md found" -ForegroundColor Green
            Write-Host "    Size: $($file.Length) bytes" -ForegroundColor Gray
            Write-Host "    Modified: $($file.TimeLastModified)" -ForegroundColor Gray

            # Read file content for SHA-256 and frontmatter extraction. -Path takes a
            # DIRECTORY and -Filename the file name separately (not one combined file path) --
            # [System.IO.Path]::GetTempFileName() returns a full file path, which left
            # -Filename unresolved and triggered an interactive prompt (found 2026-08-03,
            # same debugging pass as the two fixes above). Split explicitly instead.
            $tempFile = [System.IO.Path]::GetTempFileName()
            $tempDir = Split-Path -Path $tempFile -Parent
            $tempName = [System.IO.Path]::GetFileName($tempFile)
            Get-PnPFile -Url $skillMdPath -Path $tempDir -Filename $tempName -AsFile -Force -ErrorAction Stop | Out-Null
            $tempPath = Join-Path $tempDir $tempName

            $fileContent = Get-Content -Path $tempPath -Raw
            $fileHash = (Get-FileHash -Path $tempPath -Algorithm SHA256).Hash.ToLower()

            Write-Host "    SHA-256: $fileHash" -ForegroundColor Gray

            # Extract frontmatter
            if ($fileContent -match '---\s*([\s\S]*?)\s*---') {
                $frontmatter = $matches[1]
                if ($frontmatter -match 'name:\s*(.+)') {
                    $skillName = $matches[1].Trim()
                    Write-Host "    Frontmatter name: $skillName" -ForegroundColor Gray
                }
                if ($frontmatter -match 'description:\s*(.+)') {
                    $skillDesc = $matches[1].Trim()
                    Write-Host "    Description: $skillDesc" -ForegroundColor Gray
                }
            }

            # Check if this matches review-manual-topics
            $isReviewManualTopics = ($folderName -eq $TargetSkillName -or $skillName -eq $TargetSkillName)
            $hashMatch = ($fileHash -eq $RepositorySHA)

            $deployedSkills += [PSCustomObject]@{
                FolderName = $folderName
                Path = $folder.ServerRelativeUrl
                FileName = "SKILL.md"
                FrontmatterName = $skillName
                Description = $skillDesc
                FileSize = $file.Length
                Modified = $file.TimeLastModified
                SHA256 = $fileHash
                IsReviewManualTopics = $isReviewManualTopics
                HashMatchesRepository = $hashMatch
            }

            if ($isReviewManualTopics) {
                Write-Host "  ⚠ This is review-manual-topics" -ForegroundColor Magenta
                if ($hashMatch) {
                    Write-Host "  ✓ HASH MATCHES REPOSITORY" -ForegroundColor Green
                } else {
                    Write-Host "  ✗ HASH DIFFERS FROM REPOSITORY" -ForegroundColor Red
                }
            }

            Remove-Item -Path $tempPath -Force -ErrorAction SilentlyContinue

        } catch {
            Write-Host "  ✗ No SKILL.md found in this folder" -ForegroundColor Yellow
        }

        Write-Host ""
    }

    # Reconciliation summary
    Write-Host "=== RECONCILIATION SUMMARY ===" -ForegroundColor Cyan
    Write-Host ""

    $reviewManualTopicsDeployed = $deployedSkills | Where-Object { $_.IsReviewManualTopics }

    if ($reviewManualTopicsDeployed) {
        $skill = $reviewManualTopicsDeployed[0]
        Write-Host "review-manual-topics deployment status: DEPLOYED" -ForegroundColor Green
        Write-Host "  Path: $($skill.Path)" -ForegroundColor Gray
        Write-Host "  Deployed SHA-256: $($skill.SHA256)" -ForegroundColor Gray
        Write-Host "  Repository SHA-256: $RepositorySHA" -ForegroundColor Gray
        Write-Host "  Modified: $($skill.Modified)" -ForegroundColor Gray

        if ($skill.HashMatchesRepository) {
            Write-Host "  ✓ HASH MATCH - artifact reconciled" -ForegroundColor Green
            Write-Host ""
            Write-Host "DISPOSITION: TASK_8_ARTIFACT_ALREADY_PRESENT_AND_RECONCILED" -ForegroundColor Green
        } else {
            Write-Host "  ✗ HASH MISMATCH - artifact differs" -ForegroundColor Red
            Write-Host ""
            Write-Host "DISPOSITION: DEPLOYED_ARTIFACT_DRIFT_DETECTED" -ForegroundColor Red
        }
    } else {
        Write-Host "review-manual-topics deployment status: NOT FOUND" -ForegroundColor Yellow
        Write-Host ""
        if ($deployedSkills.Count -gt 0) {
            Write-Host "Other skills deployed:" -ForegroundColor Gray
            $deployedSkills | ForEach-Object {
                Write-Host "  - $($_.FolderName) ($($_.FrontmatterName))" -ForegroundColor Gray
            }
            Write-Host ""
            Write-Host "DISPOSITION: TASK_8_DEPLOYMENT_CANDIDATE_NOT_PRESENT" -ForegroundColor Yellow
        } else {
            Write-Host "No skills deployed yet." -ForegroundColor Gray
            Write-Host "DISPOSITION: TASK_8_NO_SKILLS_DEPLOYED" -ForegroundColor Yellow
        }
    }

    Write-Host ""
    Write-Host "End of reconciliation." -ForegroundColor Cyan

} catch {
    Write-Error "Error during reconciliation: $_"
    exit 1
}

Disconnect-PnPOnline
