<#
.SYNOPSIS
Exports stored Online page fields for offline Python link analysis.
.DESCRIPTION
Consumes the recursive files.csv. For Online .aspx library items, reads the
available CanvasContent1, LayoutWebpartsContent, WikiField and PublishingPageContent
fields. Writes one .page.json per page and page-content.csv with source/local identity.
This collects stored page content, not rendered DOM or links generated by scripts.
On-prem/static files use the download workflow instead. Live reads are user-run.
No tenant writes. Files without supported fields are reported NOT_SUPPORTED.
.EXAMPLE
pwsh -File collect-sharepoint-page-content.ps1 -InventoryCsv ./inventory/files.csv -ConfigPath ./config.psd1 -OutputDir ./page-fields
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$InventoryCsv,
    [Parameter(Mandatory = $true)][string]$OutputDir,
    [string]$ConfigPath,
    [string]$ClientId,
    [string]$TenantId
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Get-WorkbenchConnectionConfig.ps1')
if ($ConfigPath -or -not ($ClientId -and $TenantId)) {
    $config = Get-WorkbenchConnectionConfig -Path $ConfigPath
    if (-not $ClientId) { $ClientId = $config.ClientId }
    if (-not $TenantId) { $TenantId = $config.TenantId }
}
if (-not ($ClientId -and $TenantId)) { throw 'Online page collection requires ClientId and TenantId or ConfigPath.' }
$outputRoot = [IO.Path]::GetFullPath($OutputDir)
New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null
$records = [System.Collections.Generic.List[object]]::new()
$errors = 0
$pages = @(Import-Csv -LiteralPath $InventoryCsv | Where-Object { $_.FileExtension -eq 'aspx' })
foreach ($group in ($pages | Group-Object WebUrl, LibraryId)) {
    $connection = $null
    try {
        $first = $group.Group[0]
        if (-not $first.LibraryId -or -not $first.ItemId) { throw 'Page is not a library item; use static file download instead.' }
        $connection = Connect-PnPOnline -Url $first.WebUrl -ClientId $ClientId -Tenant $TenantId -Interactive -ReturnConnection
        $available = @(Get-PnPField -List $first.LibraryId -Connection $connection | ForEach-Object { $_.InternalName })
        $fields = @('CanvasContent1', 'LayoutWebpartsContent', 'WikiField', 'PublishingPageContent') | Where-Object { $_ -in $available }
        foreach ($page in $group.Group) {
            $localPath = ''
            $status = 'DOWNLOADED'
            $message = ''
            try {
                if (-not $fields) { throw [NotSupportedException]::new('No supported stored page fields; download the static file instead.') }
                $item = Get-PnPListItem -List $page.LibraryId -Id ([int]$page.ItemId) -Fields $fields -Connection $connection
                $content = [ordered]@{}
                foreach ($field in $fields) { $content[$field] = $item.FieldValues[$field] }
                $hash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($page.FileUrl))).ToLowerInvariant()
                $localPath = Join-Path $outputRoot "$hash.page.json"
                [pscustomobject]@{ SourceUrl=$page.FileUrl; WebUrl=$page.WebUrl; LibraryTitle=$page.LibraryTitle; Fields=$content } |
                    ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $localPath -Encoding utf8
            } catch {
                $errors++
                $status = if ($_.Exception -is [NotSupportedException]) { 'NOT_SUPPORTED' } else { 'FAILED' }
                $message = $_.Exception.Message
            }
            $records.Add([pscustomobject]@{ FileUrl=$page.FileUrl; WebUrl=$page.WebUrl; LibraryTitle=$page.LibraryTitle; LocalPath=$localPath; Status=$status; Message=$message })
        }
    } catch {
        foreach ($page in $group.Group) {
            $errors++
            $records.Add([pscustomobject]@{ FileUrl=$page.FileUrl; WebUrl=$page.WebUrl; LibraryTitle=$page.LibraryTitle; LocalPath=''; Status='FAILED'; Message=$_.Exception.Message })
        }
    } finally {
        if ($connection) { Disconnect-PnPOnline -Connection $connection }
    }
}
$path = Join-Path $outputRoot 'page-content.csv'
if ($records.Count) { $records | Export-Csv -LiteralPath $path -NoTypeInformation -Encoding utf8 }
else { '"FileUrl","WebUrl","LibraryTitle","LocalPath","Status","Message"' | Set-Content -LiteralPath $path -Encoding utf8 }
Write-Host "Exported $($records.Count) page-field records to $path; problems: $errors."
if ($errors) { throw 'Some page fields were unavailable; inspect page-content.csv.' }
